project_id = "pecudnxqwtugkezrsomr"

[functions.phone-advisor]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false
